version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: blueforce-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 20

volumes:
  ollama_data:
    # Reuse the same local docker volume name so partial model pulls are preserved if present
    name: ollama_data



